group: travis_latest
language: python
cache: pip
python:
    - 3.5
    - 3.6
    - 3.7
    - 3.8
#    - 3.9-dev  # need to find out if Travis CI supports Py3.9
matrix:
  allow_failures:
    - python: 3.9-dev
install: "make"
before_script:
    - make lint
script:
    - make test
after_success:
    # send report to https://coveralls.io/github/paragbaxi/qualysapi
    - coveralls
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
